# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 13:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAmbassador',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('enrollment_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sponsors', models.TextField()),
                ('ref_code', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('enrollment_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('visited_by', models.CharField(max_length=50)),
                ('visited_on', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('event_header', models.CharField(max_length=100)),
                ('event_details', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('teacher_incharge', models.CharField(max_length=300)),
                ('has_started', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('a', 'Indian Vocal Solo'), ('b', 'Western Vocal Solo'), ('c', 'Intrumental Solo'), ('d', 'Group Musical')], max_length=1, null=True)),
                ('student_name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('course', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=69)),
                ('contact_number', models.BigIntegerField()),
                ('song_name', models.CharField(default='Not Valid', max_length=300)),
                ('ref_code', models.CharField(blank=True, max_length=50)),
                ('is_csi_member', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('event_ref', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('a', 'Indian Vocal Solo'), ('b', 'Western Vocal Solo'), ('c', 'Intrumental Solo'), ('d', 'Group Musical')], max_length=1, null=True)),
                ('team_pass', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('enrollment_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(choices=[('a', 'BCA'), ('b', 'MCA')], max_length=1)),
                ('section', models.CharField(choices=[('a', 'Morning A'), ('b', 'Morning B'), ('c', 'Morning C'), ('d', 'Evening A'), ('e', 'Evening B')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.BigIntegerField()),
                ('val', models.CharField(max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cssapp.Event')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cssapp.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('created_by', 'event_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('email_id', 'event_name', 'student_name')]),
        ),
    ]
